FROM datadog/agent:latest

COPY ./conf.d/mysql.d/conf.yaml /etc/datadog-agent/conf.d/mysql.d/conf.yaml
COPY ./conf.d/nginx.d/conf.yaml /etc/datadog-agent/conf.d/nginx.d/conf.yaml
COPY ./conf.d/nodejs.d/conf.yaml /etc/datadog-agent/conf.d/nodejs.d/conf.yaml

